#!/usr/bin/env bash

export PGUSER=$POSTGRES_USER
export PGPASSWORD=$POSTGRES_PASSWORD

psql -h "$DATABASE_PORT_5432_TCP_ADDR" -p "$DATABASE_PORT_5432_TCP_PORT" -U "$PGUSER" -d "$POSTGRES_DB" <<- EOSQL
    CREATE EXTENSION ltree;
    CREATE EXTENSION intarray;
EOSQL
